name: Deploy to ECS

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      service: flask-dev-service
      cluster: flask-dev-cluster
      environment: dev   # ✅ ADD THIS
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-stage:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      service: flask-stage-service
      cluster: flask-stage-cluster
      environment: stage   # ✅ ADD THIS
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      service: flask-prod-service
      cluster: flask-prod-cluster
      environment: prod   # ✅ ADD THIS
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}