name: Deploy to ECS

on:
  push:
    branches:
      - dev
      - stage
      - main

# ✅ ADD THIS BLOCK
permissions:
  id-token: write
  contents: read

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    uses: kondeti-chaithanya/ecs-reusable-workflow/.github/workflows/ecs-deploy.yml@main
    with:
      service: flask-cluster-task-service-qccqm59g
      cluster: flask-cluster
      environment: dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-stage:
    if: github.ref == 'refs/heads/stage'
    uses: kondeti-chaithanya/ecs-reusable-workflow/.github/workflows/ecs-deploy.yml@main
    with:
      service: flask-cluster-task-service-qccqm59g
      cluster: flask-cluster
      environment: stage
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: kondeti-chaithanya/ecs-reusable-workflow/.github/workflows/ecs-deploy.yml@main
    with:
      service: flask-cluster-task-service-qccqm59g
      cluster: flask-cluster
      environment: prod
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}