name: Deploy App

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # THIS LINE LINKS ENVIRONMENT
    environment: ${{ github.ref_name }}

    uses: ./.github/workflows/ecs-deploy.yml

    with:
      service: flask-cluster-task-service-qccqm59g
      cluster: flask-cluster

    secrets: inherit